### ISSUE TITLE
Remove title option

### ISSUE THREAD

**Issue by alexiskattan** [lecar-red/bootstrapx-clickover#40]
Currently, to remove the title you have to set the 

``` css
.popover-title {
        display: none;
}
```

An option in your lib might be good.
